apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-x
  namespace: example
spec:
  selector:
    matchLabels:
      name: cloud-x
  template:
    metadata:
      labels:
        name: cloud-x
    spec:
      containers:
        - name: backend
          image: nginx
          command: ["/bin/sh", "-ec", "while :; do curl google.com; sleep 10 ; done"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-x
  namespace: example
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: cloud-x
